detectors:
  - name: custom-email-detector
    keywords:
      - email
    regex:
      email: '[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+'
    verify:
    - endpoint: http://localhost:8000/
      # unsafe must be set if the endpoint is HTTP
      unsafe: true
      headers:
      - 'Authorization: super secret authorization header'
