detectors:
  - name: custom-email-detector
    keywords:
      - email
    regex:
      email: "\\w*\\.\\w*@nobitex\\.com"
   - name: private-key-detector
    keywords:
      - private
    regex:
      private: "-----BEGIN PRIVATE KEY-----"
