name: Semgrep Full Scan

on: push

jobs:

  semgrep-full:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: Semgrep scan
        id: scan
        run: semgrep ci --config=auto --sarif -o result.sarif
      - name: Upload results
        if: failure() && steps.scan.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: result.sarif
          path: result.sarif
